In [28]:
import pandas as pd # for data processing
import folium #for creating maps
import requests #for retreiving Information
from geopy.geocoders import Nominatim #converting address to cordinates
from pandas.io.json import json_normalize #converting json to DataFrame

In [29]:
import pycaret

In [30]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [31]:
df=pd.read_csv('gdrive/My Drive/DelhiNCR Restaurants.csv')
df1 = df
df

,Restaurant_Name,Category,Pricing_for_2,Locality,Dining_Rating,Dining_Review_Count,Delivery_Rating,Delivery_Rating_Count,Website,Address,Phone_No,Latitude,Longitude,Known_For2,Known_For22
0,Rustom's,"Parsi, Street Food, North Indian, Desserts, Be...",2100,"ITO, New Delhi",4.9,1885,4.4,1844,https://www.zomato.com/ncr/rustoms-ito-new-delhi,"Delhi Parsi Anjuman, LNJP Colony, Bahadur Shah...",9.1991E+11,28.638167,77.240472,NaN,NaN
1,Cafe Lota,"Cafe, South Indian, North Indian, Beverages",1200,"Pragati Maidan, New Delhi",4.9,3748,3.9,37,https://www.zomato.com/ncr/cafe-lota-pragati-m...,"National Crafts Museum, Gate 2, Bhairon Marg, ...",9.17839E+11,28.613429,77.242471,"Pondicherry Fish Curry, Coconut Rabdi, Sabudan...","Artistic Decor, The Service, Natural Ambience,..."
2,Dum-Pukht - ITC Maurya,"Mughlai, North Indian, Desserts",5000,"ITC Maurya, Chanakyapuri, New Delhi",4.9,1371,NaN,0,https://www.zomato.com/ncr/dum-pukht-itc-maury...,"ITC Maurya, Chanakyapuri, New Delhi",9.11146E+11,28.598200,77.173661,"Royal ambiance and Mughlai cuisine, also recei...",NaN
3,Burma Burma,"Asian, Burmese, Bubble Tea, Desserts, Salad",1600,"Cyber Hub, DLF Cyber City, Gurgaon",4.9,2636,4.4,1238,https://www.zomato.com/ncr/burma-burma-dlf-cyb...,"Shop 6, Ground Floor, Building 8, Tower C, Cyb...",9.11244E+11,28.494464,77.088532,"Coconut Milk Dessert, Honey Caviar, Kaffir Lim...","Knowledgeable Staff, Authentic, Soothing Ambie..."
4,The Big Chill,"Continental, American, Italian",1500,"Khan Market, New Delhi",4.9,6487,NaN,0,https://www.zomato.com/ncr/the-big-chill-khan-...,"68-A, Khan Market, New Delhi",9.11142E+11,28.600350,77.227493,"Irish Cream Tiramisu, Penne Vodka, Mississippi...","Retro Ambience, Yummy Desserts, Big Portions, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960,Bablu Chic-Inn,"Mughlai, North Indian, Chinese, Fast Food",500,"Ashok Vihar Phase 3, New Delhi",3.9,183,4.1,545,https://www.zomato.com/ncr/bablu-chic-inn-asho...,"Shop 9, Pocket B, DDA Market, Ashok Vihar Phas...",9.2E+11,28.692473,77.178004,"Great Recommendations, Tamper Proof Packaging,...",NaN
1961,Kovilakam,South Indian,350,"Dilshad Garden, New Delhi",3.9,114,NaN,1,https://www.zomato.com/ncr/kovilakam-dilshad-g...,"F-1, Lower Ground 2, Mrignaini Chowk, Dilshad ...",9.19654E+11,28.684101,77.326725,"Kerala Parotta, Roasted Chicken, Chicken Curry...","Lip Smacking Food, Amazing Food, Owner, Good P..."
1962,Krips Restaurant,"North Indian, Chinese, Mughlai",900,"Basant Lok Market, Vasant Vihar, New Delhi",3.9,316,3.9,2977,https://www.zomato.com/ncr/krips-restaurant-va...,"59, Community Centre, Basant Lok Market, Vasan...",9.11141E+11,28.557310,77.163943,"Excellent Food, Good Ambience, Courteous Staff...",NaN
1963,Cafe 147,"Cafe, North Indian, Chinese, Kashmiri, Rolls, ...",800,"Sainik Farms, New Delhi",3.9,120,3.8,196,https://www.zomato.com/ncr/cafe-147-sainik-far...,"Shop A1/7, Ground Floor, Main IGNOU Road, Neb ...",9.19812E+11,28.510338,77.202056,"Pool, Live Music, Cafe, Environment, Good Plac...",NaN
1964,Pizzasia,"Pizza, Fast Food, Beverages",500,"Gaur City 2, Greater Noida",3.9,165,3.9,5196,https://www.zomato.com/ncr/pizzasia-gaur-city-...,"Shop 14, Ground Floor, Bhawishya India Tower, ...",9.18861E+11,28.618250,77.427417,"Cordial Staff, Great Recommendations, Mouth Wa...",NaN

In [32]:
df.isnull().sum()

Restaurant_Name            0
Category                   0
Pricing_for_2              0
Locality                   0
Dining_Rating              0
Dining_Review_Count        0
Delivery_Rating          402
Delivery_Rating_Count      0
Website                    0
Address                    0
Phone_No                   0
Latitude                   0
Longitude                  0
Known_For2               405
Known_For22              841
dtype: int64

In [33]:
df = df.drop(["Known_For2","Known_For22","Delivery_Rating","Delivery_Rating_Count","Restaurant_Name"],axis=1)
df

,Category,Pricing_for_2,Locality,Dining_Rating,Dining_Review_Count,Website,Address,Phone_No,Latitude,Longitude
0,"Parsi, Street Food, North Indian, Desserts, Be...",2100,"ITO, New Delhi",4.9,1885,https://www.zomato.com/ncr/rustoms-ito-new-delhi,"Delhi Parsi Anjuman, LNJP Colony, Bahadur Shah...",9.1991E+11,28.638167,77.240472
1,"Cafe, South Indian, North Indian, Beverages",1200,"Pragati Maidan, New Delhi",4.9,3748,https://www.zomato.com/ncr/cafe-lota-pragati-m...,"National Crafts Museum, Gate 2, Bhairon Marg, ...",9.17839E+11,28.613429,77.242471
2,"Mughlai, North Indian, Desserts",5000,"ITC Maurya, Chanakyapuri, New Delhi",4.9,1371,https://www.zomato.com/ncr/dum-pukht-itc-maury...,"ITC Maurya, Chanakyapuri, New Delhi",9.11146E+11,28.598200,77.173661
3,"Asian, Burmese, Bubble Tea, Desserts, Salad",1600,"Cyber Hub, DLF Cyber City, Gurgaon",4.9,2636,https://www.zomato.com/ncr/burma-burma-dlf-cyb...,"Shop 6, Ground Floor, Building 8, Tower C, Cyb...",9.11244E+11,28.494464,77.088532
4,"Continental, American, Italian",1500,"Khan Market, New Delhi",4.9,6487,https://www.zomato.com/ncr/the-big-chill-khan-...,"68-A, Khan Market, New Delhi",9.11142E+11,28.600350,77.227493
...,...,...,...,...,...,...,...,...,...,...
1960,"Mughlai, North Indian, Chinese, Fast Food",500,"Ashok Vihar Phase 3, New Delhi",3.9,183,https://www.zomato.com/ncr/bablu-chic-inn-asho...,"Shop 9, Pocket B, DDA Market, Ashok Vihar Phas...",9.2E+11,28.692473,77.178004
1961,South Indian,350,"Dilshad Garden, New Delhi",3.9,114,https://www.zomato.com/ncr/kovilakam-dilshad-g...,"F-1, Lower Ground 2, Mrignaini Chowk, Dilshad ...",9.19654E+11,28.684101,77.326725
1962,"North Indian, Chinese, Mughlai",900,"Basant Lok Market, Vasant Vihar, New Delhi",3.9,316,https://www.zomato.com/ncr/krips-restaurant-va...,"59, Community Centre, Basant Lok Market, Vasan...",9.11141E+11,28.557310,77.163943
1963,"Cafe, North Indian, Chinese, Kashmiri, Rolls, ...",800,"Sainik Farms, New Delhi",3.9,120,https://www.zomato.com/ncr/cafe-147-sainik-far...,"Shop A1/7, Ground Floor, Main IGNOU Road, Neb ...",9.19812E+11,28.510338,77.202056
1964,"Pizza, Fast Food, Beverages",500,"Gaur City 2, Greater Noida",3.9,165,https://www.zomato.com/ncr/pizzasia-gaur-city-...,"Shop 14, Ground Floor, Bhawishya India Tower, ...",9.18861E+11,28.618250,77.427417

In [34]:
df["Dining_Rating"].unique()

array([4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9])

In [35]:
df.loc[(df["Dining_Rating"] < 4.3) | (df["Dining_Review_Count"] < 600),"Label"] = "Bad"
df

,Category,Pricing_for_2,Locality,Dining_Rating,Dining_Review_Count,Website,Address,Phone_No,Latitude,Longitude,Label
0,"Parsi, Street Food, North Indian, Desserts, Be...",2100,"ITO, New Delhi",4.9,1885,https://www.zomato.com/ncr/rustoms-ito-new-delhi,"Delhi Parsi Anjuman, LNJP Colony, Bahadur Shah...",9.1991E+11,28.638167,77.240472,NaN
1,"Cafe, South Indian, North Indian, Beverages",1200,"Pragati Maidan, New Delhi",4.9,3748,https://www.zomato.com/ncr/cafe-lota-pragati-m...,"National Crafts Museum, Gate 2, Bhairon Marg, ...",9.17839E+11,28.613429,77.242471,NaN
2,"Mughlai, North Indian, Desserts",5000,"ITC Maurya, Chanakyapuri, New Delhi",4.9,1371,https://www.zomato.com/ncr/dum-pukht-itc-maury...,"ITC Maurya, Chanakyapuri, New Delhi",9.11146E+11,28.598200,77.173661,NaN
3,"Asian, Burmese, Bubble Tea, Desserts, Salad",1600,"Cyber Hub, DLF Cyber City, Gurgaon",4.9,2636,https://www.zomato.com/ncr/burma-burma-dlf-cyb...,"Shop 6, Ground Floor, Building 8, Tower C, Cyb...",9.11244E+11,28.494464,77.088532,NaN
4,"Continental, American, Italian",1500,"Khan Market, New Delhi",4.9,6487,https://www.zomato.com/ncr/the-big-chill-khan-...,"68-A, Khan Market, New Delhi",9.11142E+11,28.600350,77.227493,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1960,"Mughlai, North Indian, Chinese, Fast Food",500,"Ashok Vihar Phase 3, New Delhi",3.9,183,https://www.zomato.com/ncr/bablu-chic-inn-asho...,"Shop 9, Pocket B, DDA Market, Ashok Vihar Phas...",9.2E+11,28.692473,77.178004,Bad
1961,South Indian,350,"Dilshad Garden, New Delhi",3.9,114,https://www.zomato.com/ncr/kovilakam-dilshad-g...,"F-1, Lower Ground 2, Mrignaini Chowk, Dilshad ...",9.19654E+11,28.684101,77.326725,Bad
1962,"North Indian, Chinese, Mughlai",900,"Basant Lok Market, Vasant Vihar, New Delhi",3.9,316,https://www.zomato.com/ncr/krips-restaurant-va...,"59, Community Centre, Basant Lok Market, Vasan...",9.11141E+11,28.557310,77.163943,Bad
1963,"Cafe, North Indian, Chinese, Kashmiri, Rolls, ...",800,"Sainik Farms, New Delhi",3.9,120,https://www.zomato.com/ncr/cafe-147-sainik-far...,"Shop A1/7, Ground Floor, Main IGNOU Road, Neb ...",9.19812E+11,28.510338,77.202056,Bad
1964,"Pizza, Fast Food, Beverages",500,"Gaur City 2, Greater Noida",3.9,165,https://www.zomato.com/ncr/pizzasia-gaur-city-...,"Shop 14, Ground Floor, Bhawishya India Tower, ...",9.18861E+11,28.618250,77.427417,Bad

In [36]:
df["Label"] = df["Label"].fillna("Good")

In [37]:
df2 = df
df

,Category,Pricing_for_2,Locality,Dining_Rating,Dining_Review_Count,Website,Address,Phone_No,Latitude,Longitude,Label
0,"Parsi, Street Food, North Indian, Desserts, Be...",2100,"ITO, New Delhi",4.9,1885,https://www.zomato.com/ncr/rustoms-ito-new-delhi,"Delhi Parsi Anjuman, LNJP Colony, Bahadur Shah...",9.1991E+11,28.638167,77.240472,Good
1,"Cafe, South Indian, North Indian, Beverages",1200,"Pragati Maidan, New Delhi",4.9,3748,https://www.zomato.com/ncr/cafe-lota-pragati-m...,"National Crafts Museum, Gate 2, Bhairon Marg, ...",9.17839E+11,28.613429,77.242471,Good
2,"Mughlai, North Indian, Desserts",5000,"ITC Maurya, Chanakyapuri, New Delhi",4.9,1371,https://www.zomato.com/ncr/dum-pukht-itc-maury...,"ITC Maurya, Chanakyapuri, New Delhi",9.11146E+11,28.598200,77.173661,Good
3,"Asian, Burmese, Bubble Tea, Desserts, Salad",1600,"Cyber Hub, DLF Cyber City, Gurgaon",4.9,2636,https://www.zomato.com/ncr/burma-burma-dlf-cyb...,"Shop 6, Ground Floor, Building 8, Tower C, Cyb...",9.11244E+11,28.494464,77.088532,Good
4,"Continental, American, Italian",1500,"Khan Market, New Delhi",4.9,6487,https://www.zomato.com/ncr/the-big-chill-khan-...,"68-A, Khan Market, New Delhi",9.11142E+11,28.600350,77.227493,Good
...,...,...,...,...,...,...,...,...,...,...,...
1960,"Mughlai, North Indian, Chinese, Fast Food",500,"Ashok Vihar Phase 3, New Delhi",3.9,183,https://www.zomato.com/ncr/bablu-chic-inn-asho...,"Shop 9, Pocket B, DDA Market, Ashok Vihar Phas...",9.2E+11,28.692473,77.178004,Bad
1961,South Indian,350,"Dilshad Garden, New Delhi",3.9,114,https://www.zomato.com/ncr/kovilakam-dilshad-g...,"F-1, Lower Ground 2, Mrignaini Chowk, Dilshad ...",9.19654E+11,28.684101,77.326725,Bad
1962,"North Indian, Chinese, Mughlai",900,"Basant Lok Market, Vasant Vihar, New Delhi",3.9,316,https://www.zomato.com/ncr/krips-restaurant-va...,"59, Community Centre, Basant Lok Market, Vasan...",9.11141E+11,28.557310,77.163943,Bad
1963,"Cafe, North Indian, Chinese, Kashmiri, Rolls, ...",800,"Sainik Farms, New Delhi",3.9,120,https://www.zomato.com/ncr/cafe-147-sainik-far...,"Shop A1/7, Ground Floor, Main IGNOU Road, Neb ...",9.19812E+11,28.510338,77.202056,Bad
1964,"Pizza, Fast Food, Beverages",500,"Gaur City 2, Greater Noida",3.9,165,https://www.zomato.com/ncr/pizzasia-gaur-city-...,"Shop 14, Ground Floor, Bhawishya India Tower, ...",9.18861E+11,28.618250,77.427417,Bad

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
df.columns

Index(['Category', 'Pricing_for_2', 'Locality', 'Dining_Rating',
       'Dining_Review_Count', 'Website', 'Address', 'Phone_No', 'Latitude',
       'Longitude', 'Label'],
      dtype='object')

In [40]:
df['Locality'] = df['Locality'].str.split(',').str[0] 
df

,Category,Pricing_for_2,Locality,Dining_Rating,Dining_Review_Count,Website,Address,Phone_No,Latitude,Longitude,Label
0,"Parsi, Street Food, North Indian, Desserts, Be...",2100,ITO,4.9,1885,https://www.zomato.com/ncr/rustoms-ito-new-delhi,"Delhi Parsi Anjuman, LNJP Colony, Bahadur Shah...",9.1991E+11,28.638167,77.240472,Good
1,"Cafe, South Indian, North Indian, Beverages",1200,Pragati Maidan,4.9,3748,https://www.zomato.com/ncr/cafe-lota-pragati-m...,"National Crafts Museum, Gate 2, Bhairon Marg, ...",9.17839E+11,28.613429,77.242471,Good
2,"Mughlai, North Indian, Desserts",5000,ITC Maurya,4.9,1371,https://www.zomato.com/ncr/dum-pukht-itc-maury...,"ITC Maurya, Chanakyapuri, New Delhi",9.11146E+11,28.598200,77.173661,Good
3,"Asian, Burmese, Bubble Tea, Desserts, Salad",1600,Cyber Hub,4.9,2636,https://www.zomato.com/ncr/burma-burma-dlf-cyb...,"Shop 6, Ground Floor, Building 8, Tower C, Cyb...",9.11244E+11,28.494464,77.088532,Good
4,"Continental, American, Italian",1500,Khan Market,4.9,6487,https://www.zomato.com/ncr/the-big-chill-khan-...,"68-A, Khan Market, New Delhi",9.11142E+11,28.600350,77.227493,Good
...,...,...,...,...,...,...,...,...,...,...,...
1960,"Mughlai, North Indian, Chinese, Fast Food",500,Ashok Vihar Phase 3,3.9,183,https://www.zomato.com/ncr/bablu-chic-inn-asho...,"Shop 9, Pocket B, DDA Market, Ashok Vihar Phas...",9.2E+11,28.692473,77.178004,Bad
1961,South Indian,350,Dilshad Garden,3.9,114,https://www.zomato.com/ncr/kovilakam-dilshad-g...,"F-1, Lower Ground 2, Mrignaini Chowk, Dilshad ...",9.19654E+11,28.684101,77.326725,Bad
1962,"North Indian, Chinese, Mughlai",900,Basant Lok Market,3.9,316,https://www.zomato.com/ncr/krips-restaurant-va...,"59, Community Centre, Basant Lok Market, Vasan...",9.11141E+11,28.557310,77.163943,Bad
1963,"Cafe, North Indian, Chinese, Kashmiri, Rolls, ...",800,Sainik Farms,3.9,120,https://www.zomato.com/ncr/cafe-147-sainik-far...,"Shop A1/7, Ground Floor, Main IGNOU Road, Neb ...",9.19812E+11,28.510338,77.202056,Bad
1964,"Pizza, Fast Food, Beverages",500,Gaur City 2,3.9,165,https://www.zomato.com/ncr/pizzasia-gaur-city-...,"Shop 14, Ground Floor, Bhawishya India Tower, ...",9.18861E+11,28.618250,77.427417,Bad

In [41]:
columns = ["Locality","Dining_Rating","Dining_Review_Count","Latitude","Longitude"]
x = df[columns]
y = df["Label"]

In [42]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
x["Locality"] = le.fit_transform(x["Locality"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [56]:
x["Locality"].unique()

393

In [43]:
x

      Locality  Dining_Rating  Dining_Review_Count   Latitude  Longitude
0          126            4.9                 1885  28.638167  77.240472
1          226            4.9                 3748  28.613429  77.242471
2          125            4.9                 1371  28.598200  77.173661
3           63            4.9                 2636  28.494464  77.088532
4          151            4.9                 6487  28.600350  77.227493
...        ...            ...                  ...        ...        ...
1960        24            3.9                  183  28.692473  77.178004
1961        81            3.9                  114  28.684101  77.326725
1962        31            3.9                  316  28.557310  77.163943
1963       254            3.9                  120  28.510338  77.202056
1964        96            3.9                  165  28.618250  77.427417

[1965 rows x 5 columns]

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [45]:
x_train.shape

(1572, 5)

In [46]:
x_test.shape

(393, 5)

In [47]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [48]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [49]:
cm

array([[300,   9],
       [ 31,  53]])

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8982188295165394

In [65]:
cols =  ["Locality","Latitude","Longitude"]
xy = x[cols] 
xy

                  Locality   Latitude  Longitude
0                      ITO  28.638167  77.240472
1           Pragati Maidan  28.613429  77.242471
2               ITC Maurya  28.598200  77.173661
3                Cyber Hub  28.494464  77.088532
4              Khan Market  28.600350  77.227493
...                    ...        ...        ...
1960   Ashok Vihar Phase 3  28.692473  77.178004
1961        Dilshad Garden  28.684101  77.326725
1962     Basant Lok Market  28.557310  77.163943
1963          Sainik Farms  28.510338  77.202056
1964           Gaur City 2  28.618250  77.427417

[1965 rows x 3 columns]

In [66]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
xy["Locality"] = le.fit_transform(xy["Locality"])

In [67]:
x_train,x_test,y_train,y_test = train_test_split(xy,y,test_size=0.20,random_state=42)

In [68]:
from sklearn.linear_model import LogisticRegression
lf = LogisticRegression(random_state=0).fit(x_train, y_train)
y_pred = lf.predict(x_test)

In [69]:
accuracy_score(y_test,y_pred)

0.7862595419847328